version: '3.8'

volumes:
  sqlserver_data:

services:
#  api:
#    image: todolistservice
#    build:
#      context: .
#      dockerfile: ToDoListService/Dockerfile
#    ports:
#      - '8080:8080'
  rabbitmq:
    image: rabbitmq:3
    ports:
      - '5672:5672'
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - 'MSSQL_SA_PASSWORD=Passw0rd!23'
      - 'ACCEPT_EULA=Y'
    volumes:
      - sqlserver_data:/var/opt/mssql
    ports:
      - '1433:1433'
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Passw0rd!23 -Q 'SELECT 1' || exit 1
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
  sql-server-configurator:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    depends_on:
      sql-server:
        condition: service_healthy
    command:
      - "/bin/bash"
      - "-c"
      - "/opt/mssql-tools/bin/sqlcmd -S sql-server -P Passw0rd!23 -U sa -d master -v dir=/docker-entrypoint-initdb.d -i docker-entrypoint-initdb.d/init.sql"